---
title: "Clone correction, linkage-desiquilibrium and PCA"
output:
  html_document:
    keep_md: yes
editor_options:
  chunk_output_type: console
---

```{r custom_functions, echo=FALSE, message=FALSE, results='hide', warning=FALSE}
# ipak function: install and load multiple R packages.
# check to see if packages are installed. Install them if they are not, then load them into the R session.
# Source: https://gist.github.com/stevenworthington/3178163
ipak <- function(pkg){
new.pkg <- pkg[!(pkg %in% installed.packages()[,"Package"])]
if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
sapply(pkg, require, character.only = TRUE)
}

packages <- c("ggplot2","RColorBrewer","poppr", "dplyr", "knitr","kableExtra")
ipak(packages)
```


```{r Loading_data, echo=FALSE, message=FALSE}
load(file.path("..", "data", "Pyult.rda"))
```

##Clone correction analysis
```{r clones}
#Clone correction
mcc_TY <- clonecorrect(ultimhier, strata = ~County/Season, keep = c(1,2))
mcc_TY

#Locus table before and after clone correction
setPop(ultimhier) <- ~County/Season
cc <- locus_table(mcc_TY, info = FALSE)
mp <- locus_table(ultimhier, info = FALSE)

#Locus Differences after clone correction
locus_diff <- mp - cc
barplot(locus_diff[, "1-D"], ylab = "Change in Simpson's Index", xlab = "Locus",
        main = "Comparison of clone-corrected vs. uncorrected data")

```


Clone correction by population
------------------------------

```{r clone_correction_pop, fig.width=10}
plot_simp_diff <- function(pop_name, clone_corrected, un_corrected){
  # Step 1: calculate diversity for clone-corrected data
  cc <- locus_table(clone_corrected, pop = pop_name, info = FALSE)
  # Step 2: calculate diversity for uncorrected data
  uc <- locus_table(un_corrected, pop = pop_name, info = FALSE)
  # Step 3: Take the difference
  res <- uc - cc
  # Step 4: Plot Simpson's index.
  barplot(res[, "1-D"], main = pop_name, ylab = "Change in Simpson's Index", xlab = "Locus")
}

#par(mfrow = c(2, 3)) # Set up the graphics to have two rows and three columns

for (i in popNames(ultimhier)){
  plot_simp_diff(i, mcc_TY, ultimhier)
}
```

Clone correction by season
--------------------------

```{r clone_correc_season}
#clone correction by season
mcc_TS <- clonecorrect(ultimhier, strata = ~Season, keep = 1:1)
mcc_TS

#Compare before and after correction
#First Setting uncorrected pop to season
setPop(ultimhier) <- ~Season
plot_simp_diff("all",mcc_TS,ultimhier)
```

Missing data
-------------
```{r missing_data}
#Missing data looking at Season
setPop(ultimhier)<- ~Season 

#ultimhier
info_table(ultimhier, plot = TRUE)

#Genotype diversity for the hierarchy by season
poppr(ultimhier)

#Plotting missing data
miss <- info_table(ultimhier, plot = TRUE, scale = FALSE)
```

All loci, but Py62 have missing data. There are different options to follow, remove 
loci with missing data or removing by genotype.  The first one is not possible since 
it will remove 5 out of 6 loci included in this study.  However removing by genotype 
is more likely, and it will only consider genotypes with alleles.

```{r missing_data2}
#Missing data and removing loci
#Removes 5 loci
nanloc <- missingno(ultimhier, "loci")

#removing individuals
#Removes 45 individuals using default threshold 5%
nanind <- missingno(ultimhier, "geno")

#remove individuals with 2 missing loci
#Removes 15 individuals with 2 missing loci (2/nLoc) (33%)
nanind <- missingno(ultimhier, "geno", cutoff = 2/nLoc(ultimhier))
```

A third option is to replace the missing data by `0`, and maintaining the whole dataset.

```{r replace_missing_data}
#Missing data can be replace by 0
#Replacing mising data with 0
nanzero <- missingno(ultimhier, "zero")
locus_table(nanzero)
info_table(nanzero)
```

Genotype diversity with missing data removed

```{r missing_data3, fig.width=10}
#Genotype diversity for the hierarchy by season with data missing deleted
poppr(ultimhier)[,-13]
poppr(nanind)[,-13]

#Table of pop complete
mlg.table(ultimhier)

#Table of pop missing data
ult.tab <- mlg.table(nanind)

#write.table(ult.tab, sep = ",", file = "~/Documents/genotypewithtoutmissing.csv")
```

Hardy-Weinberg equilibrium at each loci
_______________________________________

```{r, eval=FALSE}
#replacing missin data with mean allele frequency ask
#hardy weinberg equilibrium
library(pegas)
nanhwe.full <- pegas::hw.test(ultimhier)
kable(nanhwe.full, format = "markdown")

#By population

nanhwe.pop  <- setPop(ultimhier, ~Season) %>% seppop() %>% lapply(pegas::hw.test, B=0)
nanhwe.mat <- sapply(nanhwe.pop, "[", i = TRUE, j = 3)

alpha <- 0.05
newmat <- nanhwe.mat
newmat[newmat > alpha] <- 1
lattice::levelplot(t(newmat))
```


Genetic richness
_________________
```{r}
library("vegan")
mon.tab <- mlg.table(ultimhier, plot = FALSE)
min_sample <- min(rowSums(mon.tab))
rarecurve(mon.tab, sample = min_sample, xlab = "Sample Size", ylab = "Expected MLGs")
title("Rarefaction of P. ultimum in 4 seasons")
mon.tab <- mlg.table(ultimhier)
```


Linkage desiquilibrium
______________________

```{r}
#Linkage desequilibrium
ultimhier %>% setPop(~Season) %>% poppr(sample= 999, total = FALSE)

#Clone correcting by season and year
setPop(ultimhier) <- ~County/Season
ult.cc <- clonecorrect(ultimhier, ~County/Season, keep = 1:2)

ult.cc %>% setPop(~Season) %>% poppr(sample= 999, total = FALSE)

```


PCA
-------

```{r}

ult.2 <- setPop(ultimhier, ~County)
Py.x <- scaleGen(ult.2, NA.method="mean", scale=FALSE)
#Py.pca <- dudi.pca(Py.x, center = FALSE, scale = FALSE)
Py.pca <- dudi.pca(Py.x, center = FALSE, scale = FALSE, nf = 3, scannf = FALSE)
Py.pca
s.label(Py.pca$li)
s.class(Py.pca$li, fac=pop(ult.2), col = funky(10))
eig.perc <- 100*Py.pca$eig/sum(Py.pca$eig)
eig.perc

library(factoextra)
fviz_eig(Py.pca)

fviz_pca_var(Py.pca,
  col.var = "contrib", # Color by contributions to the PC
  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
  repel = TRUE     # Avoid text overlapping
)

groups.season <- setPop(ult.2, ~Season) %>% pop()
groups.county <- setPop(ult.2, ~County) %>% pop()

colores.county <- c("#636363", "#bdbdbd", "#f0f0f0")
fviz_pca_ind(Py.pca,
             col.ind = groups.season, # color by groups
             #palette = colores.county,
             addEllipses = TRUE, # Concentration ellipses
             #ellipse.type = "confidence",
             legend.title = "Groups"
             )

fviz_pca_ind(Py.pca,
             col.ind = groups.county, # color by groups
             #palette = colores.county,
             addEllipses = TRUE, # Concentration ellipses
             #ellipse.type = "confidence",
             legend.title = "Groups"
             )

```

