---
title: "PCA and DAPC analyses"
output:
  html_document:
    keep_md: yes
editor_options:
  chunk_output_type: console
---

```{r custom_functions, echo=FALSE, message=FALSE, results='hide', warning=FALSE}
# ipak function: install and load multiple R packages.
# check to see if packages are installed. Install them if they are not, then load them into the R session.
# Source: https://gist.github.com/stevenworthington/3178163
ipak <- function(pkg){
new.pkg <- pkg[!(pkg %in% installed.packages()[,"Package"])]
if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
sapply(pkg, require, character.only = TRUE)
}

packages <- c("ggplot2","RColorBrewer","poppr", "dplyr", "knitr","kableExtra", "mmod")
ipak(packages)
```


```{r Loading_data, echo=FALSE, message=FALSE}
load(file.path("..","data", "Pyult.rda"))
ult.cc <- clonecorrect(ultimhier, ~County/Season, keep = 1:2)
```

PCA
-------

```{r}

ult.2 <- setPop(ultimhier, ~County)
Py.x <- scaleGen(ult.2, NA.method="mean", scale=FALSE)
#Py.pca <- dudi.pca(Py.x, center = FALSE, scale = FALSE)
Py.pca <- dudi.pca(Py.x, center = FALSE, scale = FALSE, nf = 3, scannf = FALSE)
Py.pca
s.label(Py.pca$li)
s.class(Py.pca$li, fac=pop(ult.2), col = funky(10))
eig.perc <- 100*Py.pca$eig/sum(Py.pca$eig)
eig.perc

library(factoextra)
fviz_eig(Py.pca)

fviz_pca_var(Py.pca,
  col.var = "contrib", # Color by contributions to the PC
  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
  repel = TRUE     # Avoid text overlapping
)

groups.season <- setPop(ult.2, ~Season) %>% pop()
groups.county <- setPop(ult.2, ~County) %>% pop()

colores.county <- c("#636363", "#bdbdbd", "#f0f0f0")
fviz_pca_ind(Py.pca,
             col.ind = groups.season, # color by groups
             #palette = colores.county,
             addEllipses = TRUE, # Concentration ellipses
             #ellipse.type = "confidence",
             legend.title = "Groups"
             )

fviz_pca_ind(Py.pca,
             col.ind = groups.county, # color by groups
             #palette = colores.county,
             addEllipses = TRUE, # Concentration ellipses
             #ellipse.type = "confidence",
             legend.title = "Groups"
             )

```



DAPC analysis of the Pythium ultimum
____________________________________

```{r}
library(adegenet)

ult.cc <- setPop(ult.cc, ~County)

set.seed(999)
py.xval <- xvalDapc(tab(ult.cc, NA.method = "mean"), pop(ult.cc), 
                    n.pca = 2:30,
                    n.rep = 1000,
                    parallel = "multicore", 
                    ncpus = 4L)

py.xval$DAPC
```


Using this validation, 10 PCs give us the lowest error.

```{r}
py.county <- py.xval$DAPC

scatter(py.county, 
        scree.pca = TRUE,
        bg = "grey95",
        col = "black",
        pch = seq(nlevels(strata(ult.cc)$County)),
        legend = "true",
        posi.leg = "topleft",
        posi.pca = "topright"
        )
```


##By County

```{r}
library(ggcompoplot)
ggcompoplot(py.county, setPop(ult.cc, ~County), pal = rev(funky(nlevels(strata(ult.cc)$County))), cols = 1)
```

##By Season

```{r}
ggcompoplot(py.county, setPop(ult.cc, ~Season), pal = rev(funky(nlevels(strata(ult.cc)$Season))), cols = 1)
```

##By County and Season

```{r, fig.height= 10}
ggcompoplot(py.county, setPop(ult.cc, ~County/Season), pal = rev(funky(nlevels(strata(ult.cc)$County))), cols = 1)
```


