---
title: "Population differantiation"
output:
  html_document:
    keep_md: yes
editor_options:
  chunk_output_type: console
---

```{r custom_functions, echo=FALSE, message=FALSE, results='hide', warning=FALSE}
# ipak function: install and load multiple R packages.
# check to see if packages are installed. Install them if they are not, then load them into the R session.
# Source: https://gist.github.com/stevenworthington/3178163
ipak <- function(pkg){
new.pkg <- pkg[!(pkg %in% installed.packages()[,"Package"])]
if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
sapply(pkg, require, character.only = TRUE)
}

packages <- c("ggplot2","RColorBrewer","poppr", "dplyr", "knitr","kableExtra", "mmod", "ggtree", "tibble")
ipak(packages)
```


```{r Loading_data, echo=FALSE, message=FALSE}
load(file.path("..","data", "Pyult.rda"))

ultimhier.mn <- missingno(ultimhier, "geno")
ult.cc <- clonecorrect(ultimhier.mn, ~County/Season, keep = 1:2)
```


# Assesing population structure using Hendrick's Gst

```{r}
#Gst
Gst_Hedrick(clonecorrect(ultimhier, ~County/Season, keep = 1:2))
```

# Genetic distance


## County and season using Nei's distance
```{r}
set.seed(999)
ultimhier %>%
genind2genpop(pop = ~County/Season) %>%
aboot(cutoff = 50, quiet = TRUE, sample = 1000, distance = nei.dist)

```

## Tree using Bruvo's distance

```{r}
#Repeat length
ssr.reps <- c(3, 3, 6, 6, 2, 3)

#Bruvo
setPop(ult.cc) <- ~Season
ult.tree <- bruvo.boot(ult.cc, 
                       replen = ssr.reps, 
                       sample = 1000,
                       tree ="nj", 
                       cutoff = 50, 
                       quiet = TRUE)

ult.tree$tip.label <- stringr::str_trim(ult.tree$tip.label) %>% 
  stringr::str_replace_all(" ","")


Py_metadata <- read.csv("../data/Py_metadata.csv") %>%
  select(Isolate, Origin, Season, Year, Species) %>%
  column_to_rownames("Isolate")

ult.tr2 <- ggtree(ult.tree, branch.length = "none") + 
  geom_tiplab() + 
  geom_text2(aes(label=label, subset = !is.na(as.numeric(label)) & as.numeric(label) > 50), hjust =-.3) + 
  xlim_tree(10) +
  theme_tree()
```


```{r, fig.align="center", fig.width=10, warning=FALSE}
colors <- c("#cf4661","#bf7658","#ce5d2a",
            "#c4a643","#6e7a32","#6ab544",
            "#53aa78","#4cb8d1","#7385cb",
            "#7e63cb","#c851b8","#bf679b")

#Adding heatmap
ult.tr3 <- gheatmap(ult.tr2, Py_metadata, colnames = FALSE, width = 0.6, offset = 1)

#Formatting colors and legend for heatmap
lbl <- get_heatmap_column_position(ult.tr3, by="top")
ult.tr3 + scale_fill_manual(breaks=c("Kalamazoo","Kent","Wayne","fall-11","fall-12","spring-13","2011","2012","2013",
                                       "P. ultimum ", "P. ultimum var. ultimum"), values = colors) +
  geom_text(data=lbl, aes(x, y, label=label), 
            nudge_y = 1.5, 
            nudge_x = 0.5, 
            angle=45,
            size=4)
```



# AMOVA

```{r, eval=FALSE}
#AMOVA
data(ultimhier)
ultimhier
splithierarchy(ultimhier) <- ~County/Season
ultimhier
setpop(ultimhier)<- ~Season 
ultimhier
#Replacing mising data with 0
nanzero <- missingno(ultimhier, "zero")
nanind <- missingno(ultimhier, "geno")
table(gethierarchy(ultimhier, ~County))
table(gethierarchy(nanind, ~County/Season, combine = FALSE))
ultimhieramova <- poppr.amova(ultimhier, ~County/Season)
ultimhieramova0 <- poppr.amova(nanind, ~County/Season)
ultimzhienamova <-poppr.amova(ultimhier, ~County/Season, within = FALSE)
ultimamovacc <- poppr.amova(ultimhier, ~County/Season, clonecorrect = TRUE)
ultimamovacc0 <- poppr.amova(nanind, ~County/Season, clonecorrect = TRUE)
ultimhieramova
ultimhieramova0
ultimzhienamova
ultimamovacc
ultimamovacc0
write.table(ultimhieramova$componentsofcovariance, sep = ",", file = "~/Documents/ultimhierAMOVA.csv")
write.table(ultimhier$statphi, sep = ",", file = "~/Documents/ultimhierphiAMOVA.csv")
#significance
ultimhier
set.seed(1999)
ultmsignif   <- randtest(ultimhieramova0, nrepet = 999)
Aeutccsignif <- randtest(ultimamovacc0, nrepet = 1000)
plot(ultmsignif)
ultmsignif
pdf(file = "~/Documents/significance AMOVA.pdf", width = 5, height = 5)
plot (Aeutccsignif)
dev.off()
Aeutccsignif
write.table((ultmsignif), sep = ",", file = "~/Documents/significancewithoutAMOVA.csv")
plot(Aeutccsignif)
```


